export const roleAccessMap: Record<string, string[]> = {
  administrator: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/turbidity-monitoring',
    '/ph-water-monitoring',
    '/water-level-monitoring',
    '/do-monitoring',
  ],
  moderator: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/turbidity-monitoring',
    '/ph-water-monitoring',
    '/water-level-monitoring',
    '/do-monitoring',
  ],
  user: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/turbidity-monitoring',
    '/ph-water-monitoring',
    '/water-level-monitoring',
    '/do-monitoring',
  ],
  researcher: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/turbidity-monitoring',
    '/ph-water-monitoring',
    '/water-level-monitoring',
    '/do-monitoring',
  ],

  'fishpond-operator': [
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/turbidity-monitoring',
    '/ph-water-monitoring',
    '/water-level-monitoring',
    '/do-monitoring',
  ],

  'monitoring-manager': [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/turbidity-monitoring',
    '/ph-water-monitoring',
    '/water-level-monitoring',
    '/do-monitoring',
  ],
};
