export const roleAccessMap: Record<string, string[]> = {
  all: [
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
  ],

  employee: [
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
    '/my-attendance',
    '/my-schedule',
    '/leave-requests',
    '/payslips',
    '/benefits',
    '/my-documents',
    '/my-performance',
    '/my-certificates',
  ],

  'hr-administrator': [
    '/employee-info',
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/employee-records',
    '/attendance-management',
    '/schedule-management',
    '/leave-management',
    '/payroll-management',
    '/benefits-management',
    '/documents-management',
    '/performance-management',
    '/certificates-management',
    '/reports',
  ],

  'hr-manager': [
    '/employee-info',
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
    '/employee-records',
    '/attendance-management',
    '/schedule-management',
    '/leave-management',
    '/payroll-management',
    '/benefits-management',
    '/documents-management',
    '/performance-management',
    '/certificates-management',
    '/reports',
  ],

  'hr-staff': [
    '/employee-info',
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
    '/employee-records',
    '/attendance-management',
    '/schedule-management',
    '/leave-management',
    '/payroll-management',
    '/benefits-management',
    '/documents-management',
    '/performance-management',
    '/certificates-management',
    '/reports',
  ],

  accountant: [
    '/employee-info',
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
    '/deductions',
    '/allowances',
    '/payslips-management',
    '/reimbursements',
    '/cash-advances',
    '/government-reports',
    '/tax-documents',
    '/financial-statements',
  ],

  administrator: [
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
  ],

  moderator: [
    '/dashboard',
    '/profile',
    '/account',
    '/notifications',
    '/announcements',
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
  ],
};
